routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [\App\Http\Controllers\PageController::class, 'index']);
Route::get('/about', [\App\Http\Controllers\PageController::class, 'about']);
// user
Route::name('user.')->group(function(){

    Route::view('/dashboard', 'dashboard')->middleware('auth')->name('dashboard');

    Route::get('/login', function (){
        if (Auth::check()) {
            return redirect(route('user.dashboard')); }
        return view('login');
    })->name('login');

    Route::post('/login', [\App\Http\Controllers\LoginController::class, 'login']);

    Route::get('/logout', function (){
        Auth::logout();
        return redirect('/');
    })->name('logout');

    Route::get('/registration', function (){
        if (Auth::check()) {
            return redirect(route('user.dashboard'));
        }
        return view('registration');
    })->name('registration');

    Route::post('/registration',[\App\Http\Controllers\RegisterController::class, 'save']);
});

// топики уроки
Route::name('topic.')->group(function (){
    Route::get('/topic', [\App\Http\Controllers\TopicController::class, 'index'])->name('index');
    Route::view('/topic/create', 'topic.create')->middleware('auth')->name('create');
    Route::post('/topic/store',[\App\Http\Controllers\TopicController::class, 'store'])->name('store');
    Route::get('/topic/edit/{id}', [\App\Http\Controllers\TopicController::class, 'edit'])->name('edit');
    Route::post('/topic/update', [\App\Http\Controllers\TopicController::class, 'update'])->name('update');
    Route::get('/topic/{id}/learners',[\App\Http\Controllers\TopicController::class, 'learnersedit'])->name('learnersedit');
    Route::get('/topic/go/{key}/{topicId?}:{unitId?}',[\App\Http\Controllers\TopicController::class, 'go'])->name('go');
   // Route::any('/test', [\App\Http\Controllers\TopicController::class, 'test'])->name('test');
});

//юниты
Route::name('unit.')->group(function (){
    Route::post('/unit/store', [\App\Http\Controllers\UnitController::class, 'store'])->name('store');
    Route::get('/unit/{id}', [\App\Http\Controllers\UnitController::class, 'show'])->name('show');
    Route::delete('/unit/delete', [\App\Http\Controllers\UnitController::class, 'destroy'])->name('destroy');
    Route::post('unit/update', [\App\Http\Controllers\UnitController::class, 'update'])->name('update');
});

//Ученики
Route::name('learner.')->group(function (){
    Route::get('/learners', [\App\Http\Controllers\LearnerController::class, 'index'])->name('index');
    Route::get('/learners/info', [\App\Http\Controllers\LearnerController::class, 'info'])->name('info');
    Route::post('/learner/store', [\App\Http\Controllers\LearnerController::class, 'store'])->name('store');
    Route::delete('/learner/delete', [\App\Http\Controllers\LearnerController::class, 'destroy'])->name('destroy');
    Route::post('/learner/topicstore', [\App\Http\Controllers\LearnerController::class, 'topicstore'])->name('topicstore');
});

resources/views/layouts/footer.blade.php
<script src="{{ mix('js/app.js') }}"></script>
</body>



</html>

resources/views/layouts/header.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Проект</title>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</head>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="/">Проект</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/about">О проекте</a>
                    </li>



                @auth

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Уроки (Топики)
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{{ route('topic.create') }}">Создать новый</a></li>
                            <li><a class="dropdown-item" href="{{ route('topic.index') }}">Список уроков</a></li>

                        </ul>
                    </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Ученики
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{{ route('learner.index') }}">Редактировать</a></li>
                                <li><a class="dropdown-item" href="{{ route('learner.info') }}">Инфо</a></li>

                            </ul>
                        </li>
                </ul>
                    <span class="me-2">Здравствуйте,  <strong>{{Auth::user()->email }}</strong></span>
                    <a href="/logout"><button class="btn btn-outline-danger" type="button">Выйти</button></a>
                @endauth

                @guest
                </ul>
                    <a href="/registration"><button class="me-2 btn btn-outline-primary" type="button">Регистрация</button></a>
                    <a href="/login"><button class="btn btn-outline-primary" type="button">Вход</button></a>
                @endguest


            </div>
        </div>
    </nav>
</header>
<body>