routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [\App\Http\Controllers\PageController::class, 'index']);
Route::get('/about', [\App\Http\Controllers\PageController::class, 'about']);
// user
Route::name('user.')->group(function(){

    Route::view('/dashboard', 'dashboard')->middleware('auth')->name('dashboard');

    Route::get('/login', function (){
        if (Auth::check()) {
            return redirect(route('user.dashboard')); }
        return view('login');
    })->name('login');

    Route::post('/login', [\App\Http\Controllers\LoginController::class, 'login']);

    Route::get('/logout', function (){
        Auth::logout();
        return redirect('/');
    })->name('logout');

    Route::get('/registration', function (){
        if (Auth::check()) {
            return redirect(route('user.dashboard'));
        }
        return view('registration');
    })->name('registration');

    Route::post('/registration',[\App\Http\Controllers\RegisterController::class, 'save']);
});

// топики уроки
Route::name('topic.')->group(function (){
    Route::get('/topic', [\App\Http\Controllers\TopicController::class, 'index'])->name('index');
    Route::view('/topic/create', 'topic.create')->middleware('auth')->name('create');
    Route::post('/topic/store',[\App\Http\Controllers\TopicController::class, 'store'])->name('store');
    Route::get('/topic/edit/{id}', [\App\Http\Controllers\TopicController::class, 'edit'])->name('edit');
    Route::post('/topic/update', [\App\Http\Controllers\TopicController::class, 'update'])->name('update');
    Route::get('/topic/{id}/learners',[\App\Http\Controllers\TopicController::class, 'learnersedit'])->name('learnersedit');
    Route::get('/topic/go/{key}/{topicId?}:{unitId?}',[\App\Http\Controllers\TopicController::class, 'go'])->name('go');
   // Route::any('/test', [\App\Http\Controllers\TopicController::class, 'test'])->name('test');
});

//юниты
Route::name('unit.')->group(function (){
    Route::post('/unit/store', [\App\Http\Controllers\UnitController::class, 'store'])->name('store');
    Route::get('/unit/{id}', [\App\Http\Controllers\UnitController::class, 'show'])->name('show');
    Route::delete('/unit/delete', [\App\Http\Controllers\UnitController::class, 'destroy'])->name('destroy');
    Route::post('unit/update', [\App\Http\Controllers\UnitController::class, 'update'])->name('update');
});

//Ученики
Route::name('learner.')->group(function (){
    Route::get('/learners', [\App\Http\Controllers\LearnerController::class, 'index'])->name('index');
    Route::get('/learners/info', [\App\Http\Controllers\LearnerController::class, 'info'])->name('info');
    Route::post('/learner/store', [\App\Http\Controllers\LearnerController::class, 'store'])->name('store');
    Route::delete('/learner/delete', [\App\Http\Controllers\LearnerController::class, 'destroy'])->name('destroy');
    Route::post('/learner/topicstore', [\App\Http\Controllers\LearnerController::class, 'topicstore'])->name('topicstore');
});

app/Models/Topic.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Topic extends Model
{
    use SoftDeletes;

    protected $table = 'topics';

    protected $fillable = [
        'id', // Идентификатор топика(урока)
        'name', // Название
        'is_active', // Статус топика активный\не активный
        'status' // 1 - В работе, 2 - Запущен, 0 - в архиве

    ];

    public function units(){
        return $this->hasMany(Unit::class);
    }

    public function consolidates(){
        return $this->hasMany(Consolidate::class);
    }
}

app/Http/Controllers/TopicController.php
<?php

namespace App\Http\Controllers;

use App\Models\Consolidate;
use App\Models\Topic;
use App\Models\Unit;
use Illuminate\Http\Request;

class TopicController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Topic $model)
    {
        $allTopics=Topic::all();
        //var_dump($allTopics);
        foreach ($allTopics as $topic) {
            $units=Topic::find($topic['id'])->units;
            $topic['units'] =  json_encode($units);
            $topic['unit_count'] = count($units);
        }

        return view('topic.index', ['topics' => $allTopics]);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Topic $model)
    {
        $model = $model->create($request->all());
        return redirect('topic/edit/'.$model->id);
        //print_r($model->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Topic  $topic
     * @return \Illuminate\Http\Response
     */
    public function show(Topic $topic)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Topic  $topic
     * @return \Illuminate\Http\Response
     */
    public function go(Topic $topic,$key,$topicId=0,$unitId=0){
        $error='';
        $currentUnit[0]='';
        $consolidate = Consolidate::where('url', $key)->first();

        if (!isset($consolidate)){
            $error='Ссылка не действительна!';
        } else {
             //Если не пришли значения юнит ID  и топик ID и поле сохранения пройденного юнита = 0
            // то подразумеваем что урок запущен первый раз и начинаем со стартового блока
            if ($topicId==0 && $unitId==0 && $consolidate['unit_id'] == '0') {
                //получаем стартовый юнит нужного топика
                Consolidate::where('url', $key)->update(['status'=>1]);
                $currentUnit = Unit::where([
                    ['topic_id','=',$consolidate['topic_id']],
                    ['start','=','1']])->get();
            } elseif ($topicId==-1) {
                //если приходит -1 то завершаем топик
                Consolidate::where('url',$key)->update(['unit_id'=>$topicId]);
                Consolidate::where('url', $key)->update(['status'=>2]);
                $error='Топик завершен!';

            } elseif ($topicId=='0') {

                Consolidate::where('url',$key)->update(['unit_id'=>$topicId]);
                $error='0';
            } elseif ($topicId!=0 && $unitId!=0) {

                $currentUnit = Unit::where([
                    ['topic_id','=',$topicId],
                    ['id','=',$unitId]])->get();

                   if(count($currentUnit)>0) {
                       Consolidate::where('url',$key)->update(['unit_id'=>$unitId]);
                     // dd($currentUnit[0]->id);
                   } else {
                       $error='Блок или топик не найден! Возможно он был удален!';
                   }


            } elseif ($consolidate['unit_id'] == '-1'){
                $error='0';
                Consolidate::where('url', $key)->update(['status'=>0]);
            } elseif ($consolidate['unit_id'] != '-1' && $consolidate['unit_id'] != '0' && $topicId=0 && $unitId=0){
                //не первый и не последний юнит
                $currentUnit = Unit::where([
                    ['topic_id','=',$consolidate['topic_id']],
                    ['id','=',$consolidate['unit_id']]])->get();

            }


            }



        if (count($currentUnit)==0) {$error = "Возникла неизвестная ошибка ! Попробуйте еще раз!";}
        return view('topic.go', ['unit' => $currentUnit[0],'key'=>$key, 'error'=>$error]);
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Topic  $topic
     * @return \Illuminate\Http\Response
     */
    public function edit($id, Topic $topic)
    {


        $topic=$topic->find($id);
        $topic['token']=csrf_token();
        return view('topic.edit', ['topic' => $topic]);
    }

    public function learnersedit($id,Topic $topic){





        $topic=$topic->find($id);
        $topic['units']=$topic->find($id)->units;


        return view('topic.learnersedit', ['topic' => $topic]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Topic  $topic
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Topic $model)
    {
        $dataResult = $request->all();

        $model = $model ->find($dataResult['id']);
        $model->name = $dataResult['name'];
        $model->status = $dataResult['status'];
        if(isset($dataResult['is_active'])){
            $model->is_active = 1;
        } else {
            $model->is_active = 0;
        }


        $model->update();
        return redirect('topic');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Topic  $topic
     * @return \Illuminate\Http\Response
     */
    public function destroy(Topic $topic)
    {
        //
    }
}

resources/views/topic/create.blade.php
@include("layouts.header")
<div class="container">
    <div class="row row-cols-4">
        <div class="col-6">
            <h5 class="mt-3">Страница создания урока</h5>
            <form method="post" action="{{ route('topic.store') }}" enctype="multipart/form-data">
                @csrf
                <label class="mt-5">Укажите название урока</label>
                <input type="text" class="mt-2 form-control -lg" required  name="name">
                <input type="submit" class="mt-5 btn btn-outline-info" value="Создать">
            </form>
        </div>
    </div>
</div>








@include("layouts.footer")

resources/views/topic/edit.blade.php
@include("layouts.header")



<div id="app">
    <div class="relative flex items-top justify-center min-h-screen bg-gray-100 sm:items-center py-4 sm:pt-0">
        <Topic :topic='@json($topic)'></Topic>
    </div>
</div>

@include("layouts.footer")

resources/views/topic/go.blade.php
@include("layouts.header")
@if($error=='')
    @if($unit->type == 'info')
        <div class="container">
            <div class="row row-cols-4">
                <div class="col-12 text-center">
                    <h5 class="mb-2 mt-5">Информационный блок</h5>
                    <hr>
                </div>
            </div>
            <div class="row row-cols-4">
                <div class="col-12">
                    <p mx-5><strong>Текст:</strong>
                        {{$unit->name}}
                    </p>
                </div>
            </div>
            <div class="row row-cols-4">
                <div class="col-12 text-center">
                    @foreach (json_decode($unit->exits) as $value)
                        <a href="/topic/go/{{$key}}/{{$value->link}}"><input type="button" class="mt-5 p-3 btn btn-success" value="Ознакомился"></a>
                    @endforeach
                </div>
            </div>
        </div>
    @endif

    @if($unit->type == 'choice')
        <div class="container">
            <div class="row row-cols-4">
                <div class="col-12 text-center">
                    <h5 class="mb-2 mt-5">Юнит с условием</h5>
                    <hr>
                </div>
            </div>
            <div class="row row-cols-4">
                <div class="col-12">
                    <p mx-5><strong>Текст:</strong>
                        {{$unit->name}}
                    </p>
                </div>
            </div>
            <div class="row row-cols-4">
                <div class="col-12 text-center">
                    @foreach (json_decode($unit->exits) as $value)
                        <a href="/topic/go/{{$key}}/{{$value->link}}"><input type="button" class="mt-5 mx-3 p-3 btn btn-success" value="{{$value->text}}"></a>
                    @endforeach
                </div>
            </div>
        </div>
    @endif
    @if($unit->type == 'quiz')
         <div class="container">
            <div class="row row-cols-4">
                <div class="col-12 text-center">
                    <h5 class="mb-2 mt-5">Блок с опросом</h5>
                    <hr>
                </div>
            </div>
            <div class="row row-cols-4">
                <div class="col-12">
                    <p mx-5><strong>Вопрос:</strong>
                        {{$unit->name}}
                    </p>
                </div>
            </div>
            <div class="row row-cols-4">
                <div class="col-12">
                    <p mx-5><strong>Отметьте верные ответы:</strong></p>
                    <div id="app">
                        <Quiz
                            :unit='@json($unit->param)'
                            keyhash='{{$key}}'
                            exits='@json($unit->exits)'
                        ></Quiz>
                    </div>
                </div>
            </div>
        </div>
    @endif


@else
    <div class="container">
        <div class="row row-cols-4">
            <div class="col-12 text-center">
                <hr>
                <h4 class="mb-2 mt-5">
                    @if($error=='0')
                        Топик уже завершен! <a href="/topic/go/{{$key}}/0" ><br>Пройти еще раз</a>
                     @else
                        {{$error}}
                    @endif
                </h4>
                <hr>
            </div>
        </div>
    </div>
@endif
@include("layouts.footer")

resources/views/topic/index.blade.php
@include("layouts.header")

<div class="container">
    <div class="row row-cols-4">
        <div class="col-12 text-center">
            <h5 class="mb-2 mt-3">Уроки </h5>
            <hr>
        </div>
    </div>
    <div class="accordion accordion-flush" id="accordionFlush">

        @foreach ($topics as $item)

            <div class="accordion-item">
                <h2 class="accordion-header" id="flush-heading{{$item->id}}">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse{{$item->id}}" aria-expanded="false" aria-controls="flush-collapse{{$item->id}}">
                        <div class="container">
                            <div class="row">
                                <div class="col">
                                    @if($item->is_active === 1)
                                        <span class="material-icons">done_outline</span>
                                    @else
                                        <span class="material-icons">remove_circle</span>
                                    @endif
                                </div>
                                <div class="col">
                                    ID: <strong class="mx-2">{{$item->id}}</strong>
                                </div>
                                <div class="col">
                                    Блоков:<strong class="mx-2">{{$item->unit_count}}</strong>
                                </div>
                                <div class="col">
                                    <strong class="mx-2">{{$item->name}}</strong>
                                </div>
                                <div class="col">
                                    Дата создания: <strong class="mx-2">{{$item->created_at}}</strong>
                                </div>
                            </div>
                        </div>
                    </button>
                </h2>
                <div id="flush-collapse{{$item->id}}" class="accordion-collapse collapse" aria-labelledby="flush-heading{{$item->id}}" data-bs-parent="#accordionFlush">
                    <div class="accordion-body">
                        @foreach (json_decode($item->units) as $unit)
                            @if($unit->type == 'info')
                                <p><strong class="mx-2">ID:</strong> {{ $unit->id }}
                                    <strong class="mx-2">Тип блока:</strong> Информационный
                                    <strong class="mx-2">Текст:</strong>{{ $unit->name }}
                                </p>
                                <hr>
                            @endif
                            @if($unit->type == 'choice')
                                    <p><strong class="mx-2">ID:</strong> {{ $unit->id }}
                                        <strong class="mx-2">Тип блока:</strong> Условие
                                        <strong class="mx-2">Текст:</strong>{{ $unit->name }}
                                    </p>
                                <hr>
                            @endif
                            @if($unit->type == 'quiz')

                                    <p> <strong class="mx-2">ID:</strong>  {{ $unit->id }}
                                        <strong class="mx-2">Тип блока:</strong> Блок с вопросами
                                        <strong class="mx-2">Вопрос: </strong>{{ $unit->name }}

                                    </p>
                                    <p>


                                        @foreach (json_decode($unit->param)  as $key=>$answer)

                                            {{$key}}
                                            @if($key=='allAnswer')
                                                <strong class="mx-2">Варианты ответов: </strong>@json($answer[0])
                                            @endif

                                        @endforeach


                                    </p>




                                    <hr>
                            @endif


                        @endforeach
<a href="/topic/edit/{{$item->id}}">Редактировать урок</a>
                    </div>
                </div>
            </div>



        @endforeach

    </div>
</div>

@include("layouts.footer")

resources/views/topic/learnersedit.blade.php
@include("layouts.header")



<div id="app">
    <div class="relative flex items-top justify-center min-h-screen bg-gray-100 sm:items-center py-4 sm:pt-0">
        <Learners :topic='@json($topic)'></Learners>
    </div>
</div>

@include("layouts.footer")